### ISSUE TITLE
Everlasting running runs, doing nothing

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jscockpit#227]
https://cl.aydo2.com/ays81/ays81/Runs?repo=/optvar/cockpit_repos/yves2

![screen shot 2016-11-08 at 15 08 37](https://cloud.githubusercontent.com/assets/13795109/20102164/56533640-a5c5-11e6-9545-783af77d4733.png)

And when clicking one of them I get this:

![screen shot 2016-11-08 at 15 10 21](https://cloud.githubusercontent.com/assets/13795109/20102204/868c180e-a5c5-11e6-8302-f53eb30dbf9a.png)

**Comment by rkhamis** [comment]
Fixed in latest sandbox, according to @zaibon 
@yveskerwyn  can you close this when validated?

**Comment by yveskerwyn** [comment]
No, not fixed

I just had a successful run, creating a new VDC, but in the Cockpit Portal it still shows as "running":

![screen shot 2016-11-09 at 12 27 00](https://cloud.githubusercontent.com/assets/13795109/20136954/e9b030c0-a677-11e6-86fb-1927a2a80cea.png)

![screen shot 2016-11-09 at 12 27 11](https://cloud.githubusercontent.com/assets/13795109/20136958/ee681600-a677-11e6-8fda-28a500a05891.png)

**Comment by yveskerwyn** [comment]
It is fixed, problem is purely wrong info in the Cockpit Portal, the above screenshot is from a run of 8 november (yesterday), back then we didn't have a repo yet with name "yves3"...

The real problem is this: https://github.com/Jumpscale/jscockpit/issues/230

Will close
